name: Latest blog post workflow
on:
  workflow_dispatch:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 1-7 * 1' # Runs at 00:00 on the first Monday of each month

permissions:
  contents: write

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Pull in dev.to posts
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          feed_list: "https://dev.to/feed/muzhawir"
