name: devcard
on:
  workflow_dispatch:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 1-7 * 1' # Runs at 00:00 on the first Monday of each month

jobs:
  devcard:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: devcard
        uses: dailydotdev/action-devcard@3.0.0
        with:
          user_id: ${{ secrets.USER_ID }}
          commit_message: "chore: update ${filename}"
